mybatis:
  mapper-locations: mybatis/**/*.xml

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:file:./test
    username: sa
  h2:
    console:
      enabled: true
