mybatis:
  mapper-locations: classpath:mybatis/**/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/madang
    username: root
    password: qkdldhffpt1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
